version: '3.1'
services:
  team-service:
    image: "local/statler-waldorf-corp-team-service:latest"
    build: ../statler-waldorf-corp-team-service/
    ports:
     - "5000:5000"
  location-service:
    image: "local/statler-waldorf-corp-location-service:latest"
    build: ../statler-waldorf-corp-location-service/
    ports:
     - "5001:5000"
    depends_on:
      - postgres
  location-reporter:
    image: "local/statler-waldorf-corp-location-reporter-service:latest"
    build: ../statler-waldorf-corp-location-reporter/
    ports:
      - "5002:5000"
    depends_on:
      - "rabbitmq"
  rabbitmq:
    image: rabbitmq:3.7.6-management
    ports:
      - "8080:15672"
      - "5672:5672"
  postgres: 
    image: postgres:10
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_PASSWORD=mysecretpassword
     - POSTGRES_USER=postgres
     - POSGREES_DB=locationservice