version: '3.1'
services:
  team-service:
    image: rafalpienkowski/statler-waldorf-corp-team-service:latest
    ports:
     - "5000:80"
  location-service:
    image: rafalpienkowski/statler-waldorf-corp-location-service:latest
    ports:
     - "5001:80"
    depends_on:
      - postgres
  location-reporter:
    image: rafalpienkowski/statler-waldorf-corp-location-reporter:latest
    ports:
      - "5002:500"
    depends_on:
      - "rabbitmq"
  rabbitmq:
    image: rabbitmq:3.7.6-management
    ports:
      - "8080:15672"
      - "5672:5672"
  postgres: 
    image: postgres:10
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_PASSWORD=mysecretpassword
     - POSTGRES_USER=postgres
     - POSGREES_DB=locationservice